Repository prateekbh/preact-material-components, pull requests merged in 2018-09, with the labels that each got.

#979 Replaced autobind-decorator with bind-decorator
  package-lock.json
  package.json
  ts/Base/MaterialComponent.ts
  ts/Button/index.tsx
  ts/Card/index.tsx
  ts/Checkbox/index.tsx
  ts/Chips/index.tsx
  ts/Dialog/index.tsx
  ts/Drawer/index.tsx
  ts/Elevation/index.tsx
  ts/Fab/index.tsx
  ts/FormField/index.tsx
  ts/GridList/index.tsx
  ts/Icon/index.tsx
  ts/IconButton/index.tsx
  ts/IconToggle/index.tsx
  ts/ImageList/index.tsx
  ts/LayoutGrid/index.tsx
  ts/LineRipple/index.tsx
  ts/LinearProgress/index.tsx
  ts/List/index.tsx
  ts/Menu/index.tsx
  ts/Radio/index.tsx
  ts/Select/index.tsx
  ts/Slider/index.tsx
  ts/Snackbar/index.tsx
  ts/Switch/index.tsx
  ts/TabBar/index.tsx
  ts/Tabs/index.tsx
  ts/TextField/index.tsx
  ts/Toolbar/index.tsx
  ts/TopAppBar/index.tsx
  ts/Typography/index.tsx
Labels: optimization, ready for merging

#994 fixing changes in 39
  componentsList.js
  docs/src/components/app/index.js
  docs/src/components/app/style.scss
  docs/src/components/menu/index.js
  docs/src/routes/drawer/index.js
  docs/src/routes/drawer/sample.txt
  docs/src/routes/icon-button/index.js
  docs/src/style/index.scss
  docs/tests/golden/wide/component/button.png
  docs/tests/golden/wide/component/card.png
  docs/tests/golden/wide/component/checkbox.png
  docs/tests/golden/wide/component/chips.png
  docs/tests/golden/wide/component/dialog.png
  docs/tests/golden/wide/component/drawer.png
  docs/tests/golden/wide/component/elevation.png
  docs/tests/golden/wide/component/fab.png
  docs/tests/golden/wide/component/form-field.png
  docs/tests/golden/wide/component/icon-button.png
  docs/tests/golden/wide/component/icon-toggle.png
  docs/tests/golden/wide/component/icon.png
  docs/tests/golden/wide/component/layout-grid.png
  docs/tests/golden/wide/component/list.png
  docs/tests/golden/wide/component/menu.png
  docs/tests/golden/wide/component/radio.png
  docs/tests/golden/wide/component/select.png
  docs/tests/golden/wide/component/slider.png
  docs/tests/golden/wide/component/snackbar.png
  docs/tests/golden/wide/component/switch.png
  docs/tests/golden/wide/component/tabbar.png
  docs/tests/golden/wide/component/tabs.png
  docs/tests/golden/wide/component/textfield.png
  docs/tests/golden/wide/component/theme.png
  docs/tests/golden/wide/component/toolbar.png
  docs/tests/golden/wide/component/top-app-bar.png
  docs/tests/golden/wide/component/typography.png
  docs/tests/golden/wide/index.png
  package-lock.json
  package.json
  ts/Drawer/index.tsx
  ts/IconButton/index.tsx
  ts/Menu/index.tsx
  ts/MenuSurface/index.tsx
Labels: breaking, ready for merging

#982 Optimized prerendered version of the TextField
  ts/TextField/index.tsx
Labels: enhancement, optimization

#1043 Pinned material web components
  package.json
Labels: ready for merging

#981 Minor optimizations
  ts/Checkbox/index.tsx
  ts/Drawer/index.tsx
  ts/ImageList/index.tsx
  ts/LinearProgress/index.tsx
  ts/Menu/index.tsx
  ts/Select/index.tsx
  ts/Snackbar/index.tsx
  ts/TextField/index.tsx
  ts/Typography/index.tsx
Labels: optimization, ready for merging

#980 Optimized named exports
  docs/src/components/app/index.js
  docs/src/components/menu/index.js
  package-lock.json
  ts/Button/index.tsx
  ts/Card/index.tsx
  ts/Chips/index.tsx
  ts/Dialog/index.tsx
  ts/Drawer/index.tsx
  ts/Fab/index.tsx
  ts/GridList/index.tsx
  ts/IconButton/index.tsx
  ts/ImageList/index.tsx
  ts/LayoutGrid/index.tsx
  ts/List/index.tsx
  ts/Menu/index.tsx
  ts/Select/index.tsx
  ts/TabBar/index.tsx
  ts/TextField/index.tsx
  ts/Toolbar/index.tsx
  ts/TopAppBar/index.tsx
Labels: enhancement, optimization, ready for merging

#1046 Fixed value update for floating label
  .npmignore
  ts/TextField/index.tsx
Labels: bug, ready for merging

#1047 Fixed value update on slider
  ts/Switch/index.tsx
Labels: bug, ready for merging
